
platform :ios, '14.0'

source "https://github.com/CocoaPods/Specs"
source 'https://github.com/aliyun/aliyun-specs.git'

use_frameworks!

workspace 'CIMSDK.xcworkspace'
project './CIMKit/CIMKit.xcodeproj’


target 'NoaChatSDKCore' do
project './NoaChatSDKCore/NoaChatSDKCore.xcodeproj’

  pod "AFNetworking", '4.0.1'
  pod 'CocoaAsyncSocket', '7.6.5'
  
  pod 'Logan', '1.2.8'
  pod 'LiveKitClient', '1.0.8'
  pod 'LocalLogLib', :path => './LocalLogLib/LocalLogLib.podspec'
  pod 'MMKV', '1.2.16'
  pod 'MJExtension', '3.4.0'
  pod 'NullSafe', '2.0'
  pod 'NetworkStatus', :path => './NetWorkStatus/NetWorkStatus.podspec'
  
  pod 'Protobuf', '3.21.5'
  pod 'ReactiveObjC', :inhibit_warnings => true
  
  pod 'SocketRocket', '0.6.0'
  pod 'SAMKeychain', '1.5.3'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '8.48.0'
  pod 'ZegoExpressEngine', '3.5.0'
  
end

target 'RealTimeCommunityPro' do
project './RealTimeCommunityPro/RealTimeCommunityPro.xcodeproj’


  pod 'AvoidCrash', '2.5.2'
  pod 'AliyunOSSiOS'
  pod 'ASIHTTPRequest', '1.8.2'
  pod 'AlicloudPDNS', '2.1.9'
  pod 'AWSS3'
  pod "AFNetworking", '4.0.1'
  
  pod "Alamofire", '~> 5.0'
  
  
  pod 'CocoaAsyncSocket', '7.6.5'
  pod 'DZNEmptyDataSet', '1.8.1'
  
  pod 'EncryptLib', :path => './EncryptLib/EncryptLib.podspec'
  pod "FSPlayer", :podspec => 'https://github.com/debugly/fsplayer/releases/download/1.0.2/FSPlayer.spec.json'
  pod 'FMDB', '2.7.5'
  
  pod 'IQKeyboardManager'
  pod 'Kingfisher'
  
  pod 'LiveKitClient', '1.0.8'
  pod 'Logan', '1.2.8'
  pod 'LocalLogLib', :path => './LocalLogLib/LocalLogLib.podspec'
  pod 'libOpenInstallSDK'
  pod 'LLDebugTool', :configurations => ['Debug']
  
  pod 'MJExtension', '3.4.0'
  pod 'MMKV', '1.2.16'
  pod 'MJRefresh', '3.7.5'
  pod 'MBProgressHUD', '1.2.0'
  pod 'Masonry', '1.1.0'
  pod 'NetworkStatus', :path => './NetWorkStatus/NetWorkStatus.podspec'
  pod 'NullSafe', '~> 2.0'
  
  
  pod 'Protobuf', '3.21.5'
  pod 'QCloudCOSXML', '6.4.8'
  pod 'ReactiveObjC', :inhibit_warnings => true
  
  
  pod 'SnapKit', '5.6.0'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '8.48.0'
  pod 'SDWebImageWebPCoder', '0.9.1'
  pod 'SDWebImageFLPlugin'
  pod 'SocketRocket', '0.6.0'
  pod 'SAMKeychain', '1.5.3'
  pod 'SDWebImage', '5.20.0'
  pod 'SDWebImageSVGCoder', '1.6.1'
  
  pod "SwiftyJSON", '~> 5.0'
  
  pod 'SVProgressHUD'
  
  pod 'TXLiteAVSDK_Player', '7.6.9355'
  pod 'TKThemeConfig', :path => './TKThemeConfig/TKThemeConfig.podspec'
  
  pod 'ZegoExpressEngine', '3.5.0'
    
  # ijkplayer
#  pod "IJKMediaFramework", :podspec => 'https://github.com/debugly/ijkplayer/releases/download/k0.8.9/IJKMediaFramework.spec.json'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
       target.build_configurations.each do |config|
         config.build_settings['CODE_SIGN_IDENTITY'] = ''
         config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
       end
    end
  end
end
